/**
 * Avertia API
 * API definition for Avertia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@avertia.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Trabajador de la empresa
 */
export interface Contacto {
    fechaCreacion?: Date;
    fechaActualizacion?: Date;
    titulo: string;
    nombre: string;
    telefono: string;
    email: string;
    comentarios: string;
}
