/**
 * Avertia API
 * API definition for Avertia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@avertia.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BSONObjectID } from './bSONObjectID';
import { Direccion } from './direccion';
import { Oficina } from './oficina';
import { Rol } from './rol';
import { Sociedad } from './sociedad';


/**
 * Trabajador de la empresa
 */
export interface Empleado {
    id?: string;
    fechaCreacion?: Date;
    fechaActualizacion?: Date;
    nombre: string;
    apellidos: string;
    direccion?: Direccion;
    email: string;
    telefono?: string;
    sociedad: Sociedad;
    oficina: Oficina;
    ubicacion: string;
    cargos: Array<Rol>;
    salario: string;
    otros?: string;
}

export const keyValuesEmpleado = [
    {
        value: '@Completa los datos del nuevo empleado', elements: [
            {
                key: 'nombre', value: '@nombre', formatType: 'string', customClass: 'column-size-1',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'apellidos', value: '@apellidos', formatType: 'string', customClass: 'column-size-2',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-4'
            },
            {
                key: 'email', value: '@email', formatType: 'string', customClass: 'column-size-2',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-3'
            },
            {
                key: 'telefono', value: '@telefono', formatType: 'string', customClass: 'column-size-1',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-3'
            },
        ]
    },
    {
        value: '@Completa los datos del nuevo empleado', elements: [
            {
                key: 'direccion.direccion', value: '@direccion', formatType: 'string', customClass: 'column-size-3',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-4'
            },
            {
                key: 'direccion.cp', value: '@cp', formatType: 'string',
                visible: false, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'direccion.poblacion', value: '@población', formatType: 'string',
                visible: false, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'direccion.provincia', value: '@provincia', formatType: 'string',
                visible: false, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'direccion.pais', value: '@pais', formatType: 'string',
                visible: false, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
        ]
    },
    {
        value: '@Completa los datos del nuevo empleado', elements: [
            { key: 'sociedad.nombre', value: '@sociedad', formatType: 'string', visible: true, editable: true, filtrable: true },
            { key: 'sociedad.cif', value: '@cif', formatType: 'string', visible: false, editable: false, filtrable: true },
            {
                key: 'sociedad.direccionSocial.direccion', value: '@D. social dirección', formatType: 'string',
                 customClass: 'column-size-3', visible: false, editable: false, filtrable: true
            },
            {
                key: 'sociedad.direccionSocial.poblacion', value: '@D. social población', formatType: 'string',
                 customClass: 'column-size-1', visible: false, editable: false, filtrable: true
            },
            {
                key: 'sociedad.direccionSocial.cp', value: '@D. social codigo postal', formatType: 'string',
                 customClass: 'column-size-1', visible: false, editable: false, filtrable: true
            },
            {
                key: 'sociedad.direccionSocial.provincia', value: '@D. social provincia', formatType: 'string',
                 customClass: 'column-size-1', visible: false, editable: false, filtrable: true
            },
            {
                key: 'sociedad.direccionSocial.pais', value: '@D. social pais', formatType: 'string', customClass: 'column-size-1',
                visible: false, editable: false, filtrable: true
            },
            {
                key: 'sociedad.direccionFiscal.direccion', value: '@D. fiscal direccion', formatType: 'string',
                 customClass: 'column-size-3', visible: false, editable: false, filtrable: true
            },
            {
                key: 'sociedad.direccionFiscal.cp', value: '@D. fiscal cp', formatType: 'string', customClass: 'column-size-1',
                visible: false, editable: false, filtrable: true
            },
            {
                key: 'sociedad.direccionFiscal.poblacion', value: '@D. fiscal poblacion', formatType: 'string',
                 customClass: 'column-size-1', visible: false, editable: false, filtrable: true
            },
            {
                key: 'sociedad.direccionFiscal.provincia', value: '@D. fiscal provincia', formatType: 'string',
                 customClass: 'column-size-1', visible: false, editable: false, filtrable: true
            },
            {
                key: 'sociedad.direccionFiscal.pais', value: '@D. fiscal pais', formatType: 'string', customClass: 'column-size-1',
                visible: false, editable: false, filtrable: true
            },

            {
                key: 'oficina.nombre', value: '@oficina', formatType: 'string', customClass: 'column-size-1',
                visible: true, editable: true, filtrable: true
            },
            {
                key: 'ubicacion', value: '@ubicacion', formatType: 'string', customClass: 'column-size-1',
                visible: true, editable: true, filtrable: true
            },
        ]
    },
    {
        value: '@Datos de interés del empleado', elements: [
            {
                key: 'cargos', value: '@cargos', formatType: 'string',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'salario', value: '@salario', formatType: 'string',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'otros', value: '@otros', formatType: 'string',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
        ]
    },
];
