/**
 * Avertia API
 * API definition for Avertia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@avertia.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EstadoVacaciones = 'PENDIENTE' | 'APROBADA' | 'DENEGADA';

export const EstadoVacaciones = {
    PENDIENTE: 'PENDIENTE' as EstadoVacaciones,
    APROBADA: 'APROBADA' as EstadoVacaciones,
    DENEGADA: 'DENEGADA' as EstadoVacaciones
};
