/**
 * Avertia API
 * API definition for Avertia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@avertia.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EstadoHito = 'POR_HACER' | 'RETRASADO' | 'CUMPLIDO' | 'CANCELADO';

export const EstadoHito = {
    PORHACER: 'POR_HACER' as EstadoHito,
    RETRASADO: 'RETRASADO' as EstadoHito,
    CUMPLIDO: 'CUMPLIDO' as EstadoHito,
    CANCELADO: 'CANCELADO' as EstadoHito
};
