/**
 * Avertia API
 * API definition for Avertia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@avertia.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BSONObjectID } from './bSONObjectID';
import { Perfil } from './perfil';
import { Presupuesto } from './presupuesto';
import { Seguimiento } from './seguimiento';
import { TipoProyecto } from './tipoProyecto';


export interface Evolutivo {
    id?: BSONObjectID;
    fechaCreacion?: Date;
    fechaActualizacion?: Date;
    idJira?: string;
    tipoProyecto: TipoProyecto;
    nombre: string;
    propuestaURL?: string;
    presupuesto?: Presupuesto;
    seguimiento?: Seguimiento;
    perfiles: Array<Perfil>;
}
