/**
 * Avertia API
 * API definition for Avertia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@avertia.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type Experiencia = 'baja' | 'media' | 'alta';

export const Experiencia = {
    Baja: 'baja' as Experiencia,
    Media: 'media' as Experiencia,
    Alta: 'alta' as Experiencia
};
