/**
 * Avertia API
 * API definition for Avertia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@avertia.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BSONObjectID } from './bSONObjectID';
import { Comentario } from './comentario';
import { EstadoHito } from './estadoHito';


export interface Hito {
    id?: BSONObjectID;
    fechaCreacion?: Date;
    fechaActualizacion?: Date;
    nombre: string;
    fecha: Date;
    descripcion: string;
    comentarios?: Array<Comentario>;
    estado: EstadoHito;
}
