/**
 * Avertia API
 * API definition for Avertia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@avertia.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BSONObjectID } from './bSONObjectID';
import { Direccion } from './direccion';
import { Oficina } from './oficina';
import { Rol } from './rol';
import { Sociedad } from './sociedad';


/**
 * Trabajador de la empresa
 */
export interface Perfil {
    id?: string;
    fechaCreacion?: Date;
    fechaActualizacion?: Date;
    nombre: string;
    apellidos: string;
    direccion?: Direccion;
    email: string;
    telefono?: string;
    sociedad: Sociedad;
    oficina: Oficina;
    ubicacion: string;
    cargos: Array<Rol>;
    salario: string;
    otros?: string;
}
