/**
 * Avertia API
 * API definition for Avertia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@avertia.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BSONObjectID } from './bSONObjectID';
import { Direccion } from './direccion';


/**
 * Sociedad Object
 */
export interface Sociedad {
    id?: string;
    nombre: string;
    cif: string;
    direccionSocial: Direccion;
    direccionFiscal: Direccion;
    fechaCreacion?: Date;
    fechaActualizacion?: Date;
}

export const keyValuesSociedad = [
    {
        value: '@Completa el nombre de la nueva sociedad', elements: [
            {
                key: 'nombre', value: '@nombre', formatType: 'string', visible: true, editable: true, filtrable: true,
                customClassInput: 'input-width-4'
            },
            {
                key: 'cif', value: '@cif', formatType: 'string', visible: true, editable: true, filtrable: true
                , customClassInput: 'input-width-1'
            }]
    },
    {
        value: '@Completa la Direccion social', elements: [
            {
                key: 'direccionSocial.direccion', value: '@D. social dirección', formatType: 'string', customClass: 'column-size-3',
                visible: false, editable: true, filtrable: true, customClassInput: 'input-width-4'
            },
            {
                key: 'direccionSocial.poblacion', value: '@D. social población', formatType: 'string', customClass: 'column-size-1',
                visible: false, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'direccionSocial.cp', value: '@D. social codigo postal', formatType: 'string', customClass: 'column-size-1',
                visible: false, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'direccionSocial.pais', value: '@D. social pais', formatType: 'string', customClass: 'column-size-1',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'direccionSocial.provincia', value: '@D. social provincia', formatType: 'string', customClass: 'column-size-1',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
        ]
    },
    {
        value: '@Completa la Direccion fiscal', elements: [
            {
                key: 'direccionFiscal.direccion', value: '@D. fiscal direccion', formatType: 'string', customClass: 'column-size-3',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-4'
            },
            {
                key: 'direccionFiscal.cp', value: '@D. fiscal cp', formatType: 'string', customClass: 'column-size-1',
                visible: true, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'direccionFiscal.poblacion', value: '@D. fiscal poblacion', formatType: 'string', customClass: 'column-size-1',
                visible: false, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'direccionFiscal.provincia', value: '@D. fiscal provincia', formatType: 'string', customClass: 'column-size-1',
                visible: false, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
            {
                key: 'direccionFiscal.pais', value: '@D. fiscal pais', formatType: 'string', customClass: 'column-size-1',
                visible: false, editable: true, filtrable: true, customClassInput: 'input-width-2'
            },
        ]
    },
];

export const groupsSociedad = [
    {
        nombre: '@Dirección Social',
        columns: ['direccionSocial.direccion', 'direccionSocial.cp', 'direccionSocial.provincia', 'direccionSocial.pais']
    }
];
