/**
 * Avertia API
 * API definition for Avertia
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@avertia.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BSONObjectID } from './bSONObjectID';
import { EstadoVacaciones } from './estadoVacaciones';
import { PeriodoVacaciones } from './periodoVacaciones';


/**
 * Vacaciones
 */
export interface Vacaciones {
    id?: BSONObjectID;
    fechaCreacion?: Date;
    fechaActualizacion?: Date;
    estado?: EstadoVacaciones;
    comentario?: string;
    respuesta?: string;
    vacaciones: Array<PeriodoVacaciones>;
}
